FROM node:14-alpine

RUN yarn global add @quasar/cli

COPY ./package.json /package.json
RUN yarn install

ADD ./  /code/
WORKDIR /code

RUN rm -rf /code/node_modules
RUN mv /node_modules /code/

CMD ["quasar", "dev"]
