version: "3.8"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure
    volumes:
      - type: bind
        source: ./src
        target: /code/src
